# Generated by Django 5.2.5 on 2025-09-10 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('debates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='agent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agent'),
        ),
    ]
